//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvilDataUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedDataStatus
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerValue { get; set; }
        public string File { get; set; }
        public string Hash { get; set; }
        public string UploadStatus { get; set; }
        public string UploadGuid { get; set; }
        public System.DateTime UploadDate { get; set; }
    }
}
